<?php
$stats=[["Overall compliance","70%","+4.8% this month","good"],["Tasks completed","18 / 21","3 tasks pending","info"],["Open findings","2","1 high priority","warning"],["Temperature checks","96%","All critical limits met","good"]];
$tasks=[["Daily hygiene inspection","Production Area","Completed","good"],["Refrigerator temperature check","Cold Room 1","Completed","good"],["Cleaning verification","Processing Area","Pending","warning"],["Raw material receiving check","Receiving Bay","Completed","good"],["Pest control inspection","Storage Area","Pending","warning"]];
$temps=[["Cold Room 1","4.2 °C","0–5 °C","Normal","good"],["Cold Room 2","7.8 °C","0–5 °C","Attention","warning"],["Freezer","-18.4 °C","≤ -18 °C","Normal","good"]];
$activity=[["✓","Cleaning record completed","Production Area","12 min ago"],["!","Temperature above target","Cold Room 2","38 min ago"],["✓","Supplier inspection completed","Receiving Bay","1 hr ago"],["✓","Hygiene checklist submitted","Production Area","2 hrs ago"]];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FoodSafe — Compliance Dashboard</title><link rel="stylesheet" href="css/style.css"></head><body>
<div class="app"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">✓</div><div>Food<span>Safe</span></div></div><div class="site-select"><span class="live-dot"></span><div><small>FACILITY</small><strong>FreshBite Foods</strong></div><b>⌄</b></div><nav>
<a class="active" href="index.php">⌂ <span>Dashboard</span></a><a href="checklist.php">✓ <span>Safety Checklist</span></a><a href="temperature.php">° <span>Temperature</span></a><a href="cleaning.php">✦ <span>Cleaning Records</span></a><a href="suppliers.php">▤ <span>Suppliers</span></a><a href="non-conformances.php">! <span>Non-Conformances</span></a><a href="reports.php">▥ <span>Reports</span></a></nav>
<div class="sidebar-bottom"><div class="compliance-mini"><small>MONTHLY COMPLIANCE</small><strong>92%</strong><div class="bar"><i style="width:92%"></i></div><span>Excellent standing</span></div><div class="user"><div class="avatar">U</div><div><strong>Ufuoma</strong><small>Food Safety Manager</small></div></div></div></aside>
<main><header class="topbar"><button class="mobile-menu" onclick="document.getElementById('sidebar').classList.toggle('open')">☰</button><div class="crumb">Food Safety / <strong>Dashboard</strong></div><div class="top-actions"><button class="icon">☾</button><button class="icon notify">♧<i></i></button><div class="avatar small">U</div></div></header>
<div class="content"><section class="hero"><div><p class="eyebrow">WEDNESDAY, 26 AUGUST 2026</p><h1>Good morning, Ufuoma.</h1><p>Here's your food safety overview for today.</p></div><a class="button" href="checklist.php">+ Start inspection</a></section>
<section class="stats"><?php foreach($stats as $s): ?><article class="stat"><div class="stat-head"><span><?=$s[0]?></span><b class="<?=$s[3]?>"><?=$s[3]==="good"?"✓":($s[3]==="warning"?"!":"↗")?></b></div><strong><?=$s[1]?></strong><small class="<?=$s[3]?>"><?=$s[2]?></small></article><?php endforeach;?></section>
<div class="grid"><section class="panel"><div class="panel-head"><div><h2>Today's safety tasks</h2><p>Daily monitoring activities</p></div><a href="checklist.php">View checklist →</a></div><div class="task-list"><?php foreach($tasks as $t): ?><div class="task"><div class="task-check <?=$t[3]?>"><?=$t[3]==="good"?"✓":"!"?></div><div><strong><?=$t[0]?></strong><small><?=$t[1]?></small></div><span class="badge <?=$t[3]?>"><?=$t[2]?></span></div><?php endforeach;?></div></section>
<section class="panel"><div class="panel-head"><div><h2>Temperature monitoring</h2><p>Latest critical control readings</p></div><a href="temperature.php">View records →</a></div><?php foreach($temps as $t): ?><div class="temp"><div class="temp-icon">°</div><div><strong><?=$t[0]?></strong><small>Limit: <?=$t[2]?></small></div><div class="temp-value"><b class="<?=$t[4]?>"><?=$t[1]?></b><span class="<?=$t[4]?>">● <?=$t[3]?></span></div></div><?php endforeach;?><div class="temp-note">⚠ Cold Room 2 requires attention. Verify the reading and record corrective action.</div></section></div>
<div class="grid bottom"><section class="panel"><div class="panel-head"><div><h2>Compliance trend</h2><p>Last 7 days</p></div><strong class="score">92%</strong></div><div class="chart"><div class="y"><span>100</span><span>90</span><span>80</span><span>70</span></div><div class="chart-body"><div class="lines"><i></i><i></i><i></i><i></i></div><svg viewBox="0 0 650 220" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#35b987" stop-opacity=".25"/><stop offset="1" stop-color="#35b987" stop-opacity="0"/></linearGradient></defs><path class="area" d="M0 160 C50 145 65 135 105 145 S170 120 210 130 S275 95 320 112 S390 75 430 92 S500 80 545 58 S610 70 650 38 L650 220 L0 220Z"/><path class="line" d="M0 160 C50 145 65 135 105 145 S170 120 210 130 S275 95 320 112 S390 75 430 92 S500 80 545 58 S610 70 650 38"/></svg><div class="x"><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span></div></div></div></section>
<section class="panel"><div class="panel-head"><div><h2>Recent activity</h2><p>Latest food safety events</p></div><a href="reports.php">View all →</a></div><div class="activity"><?php foreach($activity as $a): ?><div><span class="activity-icon <?=$a[0]==="!"?"warn":""?>"><?=$a[0]?></span><p><strong><?=$a[1]?></strong><small><?=$a[2]?></small></p><time><?=$a[3]?></time></div><?php endforeach;?></div></section></div></div><footer>FoodSafe Compliance Platform <span>• Demo data for portfolio/assignment</span></footer></main></div><script src="js/app.js"></script></body></html>